# Generated by Django 4.0 on 2021-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(max_length=45, verbose_name='Nombre Finca')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('telefono', models.BigIntegerField()),
                ('ubicacion', models.CharField(max_length=80, verbose_name='Ubicación')),
                ('departamento', models.CharField(max_length=45, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=45, verbose_name='Municipio')),
                ('extension', models.CharField(max_length=80, verbose_name='Extensión')),
                ('propietario', models.CharField(max_length=45, verbose_name='Propietario')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
            ],
        ),
    ]
