# Generated by Django 4.0 on 2021-12-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('precioLibra', models.CharField(max_length=30)),
                ('cosecha', models.DateField()),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('fase', models.DateField(max_length=50, null=True, verbose_name='Fase')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
    ]
